default['spark']['version']                    = 'spark-2.1.1-bin-hadoop2.7'
default['spark']['download']                   = 'axel https://archive.apache.org/dist/spark/spark-2.1.1/spark-2.1.1-bin-hadoop2.7.tgz'
default['spark']['MASTER_HOST']                = 'shashiudawa1.mylabserver.com'
default['spark']['MASTER_PORT']                = 443
default['spark']['WORKER_MEMORY']              = '196G'
default['spark']['WORKER_INSTANCES']           = 1
default['spark']['EXECUTOR_INSTANCES']         = 0
default['spark']['WORKER_CORES']               = 1
default['spark']['DRIVER_CORES']               = 1
default['spark']['DRIVER_MEMORY']              = '64g'
default['spark']['master_rest_port']           = 6066
default['spark']['cores_max']                  = 1
default['spark']['deploy_defaultCores']        = 1
default['spark']['ingester_spark_work_folder'] = '/var/log/ingester_spark_work_folder/'
default['spark']['local_dir']                  = '/var/log/ingester_spark_work_folder/local_dir'
default['spark']['driver_memory']              = '64g'
default['spark']['worker_nodes']               = 'shashiudawa6.mylabserver.com'
default['spark']['config_owner']               = 'root'
default['spark']['config_group']               = 'root'
default['spark']['config_mode']                = '0755'
default['spark']['service_name']               = 'spark-uspto'
default['spark']['service_chkconfig_exec ']    = "Check config for #{node['spark']['service_name']} service"
